name: create draft release

on:
  push:
    branches:
    - test-release-activation
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      applicable: ${{ steps.check-commit-message.outputs.applicable }}
    steps:
    - name: Check commit message
      id: check-commit-message
      run: |
        str=${{ github.event.head_commit.message }}
        regex="^release\s*:\s*(v[0-9]+\.[0-9]+\.[0-9]+|[0-9]+\.[0-9]+\.[0-9]+)\s*$"
        if [[ $str =~ $regex ]]; then echo "::set-output name=applicable::true"; else echo "::set-output name=applicable::false"

  release:
    if: ${{ needs.check.outputs.applicable }} == "true"
    name: Create Tag and Draft Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Calculate Tag and release names
      run: |
        t=$(echo ${{ github.event.head_commit.message }} | sed -ne 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
        if [ -z "$t" ]; then
        echo Malformed commit message; failed to extract semVer tag
        return 1
        fi
        echo TAG_NAME="v${t}" >> $GITHUB_ENV
        echo RELEASE_NAME="v${t} Release" >> $GITHUB_ENV
